name = "HyrodiumHome"
uuid = "67e7e186-7d6d-4ad4-9306-63d5d0b84fec"
authors = ["hyrodium <hyrodium@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "0.26, 0.27"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
