name = "HyrodiumHome"
uuid = "67e7e186-7d6d-4ad4-9306-63d5d0b84fec"
authors = ["hyrodium <hyrodium@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
